---
apiVersion: v1
kind: Namespace
metadata:
    name: c9s-vlan
    labels:
        pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vlan-client1-files
  namespace: c9s-vlan
data:
  configs-client.sh: |-
    #!/bin/bash

    # client id
    ID=$1

    ###### eth1 ######
    # no tagging
    ip addr add 10.1.0.${ID}/30 dev eth1
    ip link set dev eth1 address aa:c1:ab:00:00:0${ID}

    # single tag VID 10
    ip link add name eth1.10 link eth1 type vlan id 10
    ip addr add 10.1.1.${ID}/30 dev eth1.10
    ip link set dev eth1.10 address aa:c1:ab:00:01:0${ID}
    ip link set dev eth1.10 up

    # single tag VID 11
    ip link add name eth1.11 link eth1 type vlan id 11
    ip addr add 10.1.2.${ID}/30 dev eth1.11
    ip link set dev eth1.11 address aa:c1:ab:00:02:0${ID}
    ip link set dev eth1.11 up

    # qinq outer tag 12, inner tag 13
    ip link add name eth1.12 link eth1 type vlan proto 802.1q id 12 # outer
    ip link add name eth1.12.13 link eth1.12 type vlan proto 802.1q id 13 # inner tag
    ip addr add 10.1.3.${ID}/30 dev eth1.12.13
    ip link set dev eth1.12 address aa:c1:ab:03:00:0${ID}
    ip link set dev eth1.12 up
    ip link set dev eth1.12.13 address aa:c1:ab:03:03:0${ID}
    ip link set dev eth1.12.13 up

    # explicit null tag case is not covered
    # since it is a quirky case that varies from vendor to vendor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vlan-client2-files
  namespace: c9s-vlan
data:
  configs-client.sh: |-
    #!/bin/bash

    # client id
    ID=$1

    ###### eth1 ######
    # no tagging
    ip addr add 10.1.0.${ID}/30 dev eth1
    ip link set dev eth1 address aa:c1:ab:00:00:0${ID}

    # single tag VID 10
    ip link add name eth1.10 link eth1 type vlan id 10
    ip addr add 10.1.1.${ID}/30 dev eth1.10
    ip link set dev eth1.10 address aa:c1:ab:00:01:0${ID}
    ip link set dev eth1.10 up

    # single tag VID 11
    ip link add name eth1.11 link eth1 type vlan id 11
    ip addr add 10.1.2.${ID}/30 dev eth1.11
    ip link set dev eth1.11 address aa:c1:ab:00:02:0${ID}
    ip link set dev eth1.11 up

    # qinq outer tag 12, inner tag 13
    ip link add name eth1.12 link eth1 type vlan proto 802.1q id 12 # outer
    ip link add name eth1.12.13 link eth1.12 type vlan proto 802.1q id 13 # inner tag
    ip addr add 10.1.3.${ID}/30 dev eth1.12.13
    ip link set dev eth1.12 address aa:c1:ab:03:00:0${ID}
    ip link set dev eth1.12 up
    ip link set dev eth1.12.13 address aa:c1:ab:03:03:0${ID}
    ip link set dev eth1.12.13 up

    # explicit null tag case is not covered
    # since it is a quirky case that varies from vendor to vendor
---
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: vlan
  namespace: c9s-vlan
spec:
  deployment:
    filesFromConfigMap:
        client1:
          - filePath: configs/client.sh
            configMapName: vlan-client1-files
            configMapPath: configs-client.sh
            mode: execute
        client2:
          - filePath: configs/client.sh
            configMapName: vlan-client2-files
            configMapPath: configs-client.sh
            mode: execute
  naming: non-prefixed
  definition:
    containerlab: |-
          name: vlan

          topology:
            kinds:
              nokia_srlinux:
                image: ghcr.io/nokia/srlinux:24.10.1
                startup-config: configs/srl.cfg
              
              linux:
                image: ghcr.io/srl-labs/alpine

            nodes:
              srl:
                kind: nokia_srlinux

              client1:
                kind: linux
                binds:
                  - configs/client.sh:/config.sh
                exec:
                  - "ash -c '/config.sh 1'"      
              client2:
                kind: linux    
                binds:
                  - configs/client.sh:/config.sh
                exec:
                  - "ash -c '/config.sh 2'"      

            links:
              # links between client1 and srl
              - endpoints: [client1:eth1, srl:e1-1]    

              # links between client2 and srl
              - endpoints: [srl1:e1-1, client2:eth1]

